In [232]:
import pandas as pd
import sklearn

In [233]:
filepath = 'GroupExam2024_data_and_documentation/elektronisk-rapportering-ers-2018-fangstmelding-dca-simple.csv'
df = pd.read_csv(filepath, sep=';', decimal=',')
pd.set_option('display.max_columns', None)
df.head()

,Melding ID,Meldingstidspunkt,Meldingsdato,Meldingsklokkeslett,Starttidspunkt,Startdato,Startklokkeslett,Startposisjon bredde,Startposisjon lengde,Hovedområde start (kode),Hovedområde start,Lokasjon start (kode),Havdybde start,Stopptidspunkt,Stoppdato,Stoppklokkeslett,Varighet,Fangstår,Stopposisjon bredde,Stopposisjon lengde,Hovedområde stopp (kode),Hovedområde stopp,Lokasjon stopp (kode),Havdybde stopp,Trekkavstand,Redskap FAO (kode),Redskap FAO,Redskap FDIR (kode),Redskap FDIR,Hovedart FAO (kode),Hovedart FAO,Hovedart - FDIR (kode),Art FAO (kode),Art FAO,Art - FDIR (kode),Art - FDIR,Art - gruppe (kode),Art - gruppe,Rundvekt,Lengdegruppe (kode),Lengdegruppe,Bruttotonnasje 1969,Bruttotonnasje annen,Bredde,Fartøylengde
0,1497177,01.01.2018,01.01.2018,00:00,31.12.2017,31.12.2017,00:00,-60.350,-46.133,NaN,NaN,NaN,-2740,01.01.2018,01.01.2018,00:00,1440,2018,-60.400,-46.150,NaN,NaN,NaN,-805,5649.0,OTM,"Flytetrål, otter",53.0,Flytetrål,KRI,Antarktisk krill,2513.0,KRI,Antarktisk krill,2513.0,Antarktisk krill,506.0,Antarktisk krill,706714.0,5.0,28 m og over,9432.0,NaN,19.87,133.88
1,1497178,01.01.2018,01.01.2018,00:00,30.12.2017 23:21,30.12.2017,23:21,74.885,16.048,20.0,Bjørnøya,7.0,-335,31.12.2017 04:16,31.12.2017,04:16,295,2017,74.914,15.969,20.0,Bjørnøya,7.0,-334,3970.0,OTB,"Bunntrål, otter",51.0,Bunntrål,HAD,Hyse,1027.0,HAD,Hyse,1027.0,Hyse,202.0,Hyse,9594.0,5.0,28 m og over,1476.0,NaN,12.60,56.80
2,1497178,01.01.2018,01.01.2018,00:00,30.12.2017 23:21,30.12.2017,23:21,74.885,16.048,20.0,Bjørnøya,7.0,-335,31.12.2017 04:16,31.12.2017,04:16,295,2017,74.914,15.969,20.0,Bjørnøya,7.0,-334,3970.0,OTB,"Bunntrål, otter",51.0,Bunntrål,HAD,Hyse,1027.0,COD,Torsk,1022.0,Torsk,201.0,Torsk,8510.0,5.0,28 m og over,1476.0,NaN,12.60,56.80
3,1497178,01.01.2018,01.01.2018,00:00,30.12.2017 23:21,30.12.2017,23:21,74.885,16.048,20.0,Bjørnøya,7.0,-335,31.12.2017 04:16,31.12.2017,04:16,295,2017,74.914,15.969,20.0,Bjørnøya,7.0,-334,3970.0,OTB,"Bunntrål, otter",51.0,Bunntrål,HAD,Hyse,1027.0,GHL,Blåkveite,2313.0,Blåkveite,301.0,Blåkveite,196.0,5.0,28 m og over,1476.0,NaN,12.60,56.80
4,1497178,01.01.2018,01.01.2018,00:00,30.12.2017 23:21,30.12.2017,23:21,74.885,16.048,20.0,Bjørnøya,7.0,-335,31.12.2017 04:16,31.12.2017,04:16,295,2017,74.914,15.969,20.0,Bjørnøya,7.0,-334,3970.0,OTB,"Bunntrål, otter",51.0,Bunntrål,HAD,Hyse,1027.0,POK,Sei,1032.0,Sei,203.0,Sei,134.0,5.0,28 m og over,1476.0,NaN,12.60,56.80

In [234]:
df.dtypes

Melding ID                    int64
Meldingstidspunkt            object
Meldingsdato                 object
Meldingsklokkeslett          object
Starttidspunkt               object
Startdato                    object
Startklokkeslett             object
Startposisjon bredde        float64
Startposisjon lengde        float64
Hovedområde start (kode)    float64
Hovedområde start            object
Lokasjon start (kode)       float64
Havdybde start                int64
Stopptidspunkt               object
Stoppdato                    object
Stoppklokkeslett             object
Varighet                      int64
Fangstår                      int64
Stopposisjon bredde         float64
Stopposisjon lengde         float64
Hovedområde stopp (kode)    float64
Hovedområde stopp            object
Lokasjon stopp (kode)       float64
Havdybde stopp                int64
Trekkavstand                float64
Redskap FAO (kode)           object
Redskap FAO                  object
Redskap FDIR (kode)         float64
Redskap FDIR                 object
Hovedart FAO (kode)          object
Hovedart FAO                 object
Hovedart - FDIR (kode)      float64
Art FAO (kode)               object
Art FAO                      object
Art - FDIR (kode)           float64
Art - FDIR                   object
Art - gruppe (kode)         float64
Art - gruppe                 object
Rundvekt                    float64
Lengdegruppe (kode)         float64
Lengdegruppe                 object
Bruttotonnasje 1969         float64
Bruttotonnasje annen        float64
Bredde                      float64
Fartøylengde                float64
dtype: object

Meldingsdato, Meldingsklokkeslett, startdato, startklokkeslett, 
Melding ID                    Samle unike båter
Meldingstidspunkt            object - Konverter til datetime
Meldingsdato                 dropp
Meldingsklokkeslett          dropp
Starttidspunkt               object - konverter til datetime
Startdato                    dropp
Startklokkeslett             dropp
Startposisjon bredde        float64
Startposisjon lengde        float64
Hovedområde start (kode)    float64
Hovedområde start            dropp
Lokasjon start (kode)       dropp
Havdybde start                int64
Stopptidspunkt               object
Stoppdato                    dropp
Stoppklokkeslett             dropp
Varighet                      int64
Fangstår                      dropp
Stopposisjon bredde         float64 - Muligens droppe
Stopposisjon lengde         float64 - muligens droppe
Hovedområde stopp (kode)    dropp - kan være nyttig i utsilingsprosessen å berre fokusere på eit område. 
Hovedområde stopp            dropp
Lokasjon stopp (kode)       dropp
Havdybde stopp                int64
Trekkavstand                float64
Redskap FAO (kode)           object
Redskap FAO                  object - dropp
Redskap FDIR (kode)         dropp
Redskap FDIR                 dropp
Hovedart FAO (kode)          dropp 
Hovedart FAO                 dropp
Hovedart - FDIR (kode)      float64
Art FAO (kode)               dropp
Art FAO                      dropp
Art - FDIR (kode)           float64
Art - FDIR                   dropp
Art - gruppe (kode)         float64
Art - gruppe                 dropp
Rundvekt                    float64
Lengdegruppe (kode)         float64
Lengdegruppe                 dropp
Bruttotonnasje 1969         float64 - slå sammen denne og neste
Bruttotonnasje annen        float64
Bredde                      dropp
Fartøylengde                dropp

In [235]:
# Hvor mange fisketokter som er registrert for hvilken type fisk. (de 1000 minste er silt ut)
unique_fish_types = df.groupby(['Art - FDIR', 'Art - FDIR (kode)'], ).size()
unique_fish_types_df = unique_fish_types.reset_index(name='Count')  # R
unique_fish_types_sorted = unique_fish_types_df.sort_values(by = 'Count', ascending = False, )
filtered_df = unique_fish_types_sorted[unique_fish_types_sorted['Count'] <= 100]
filtered_df

                  Art - FDIR  Art - FDIR (kode)  Count
70  Reke av  Pandalusslekten             2523.0    100
71        Rognkjeks (felles)             2221.0     98
15                  Blåkjeft             2205.0     89
86            Skater, uspes.              559.0     84
74                  Rødknurr             2214.0     81
..                       ...                ...    ...
23       Bukstripet pelamide             2018.0      1
19                 Blæretang             2817.0      1
43                   Isskate              552.0      1
73            Rød kråkebolle             2662.0      1
87               Skjeggtorsk             1037.0      1

[61 rows x 3 columns]

In [236]:
fish_weigh = df.groupby(['Art - FDIR', 'Art - FDIR (kode)'], ).size()
fish_weigh_df = fish_weigh.reset_index(name='Count')  # R
fish_weigh_sorted = fish_weigh_df.sort_values(by = 'Count', ascending = False, )
filtered_df = fish_weigh_sorted[fish_weigh_sorted['Count'] >= 1000]
fish_weigh

Art - FDIR        Art - FDIR (kode)
Akkar             2634.0                252
Annen blekksprut  2639.0                  8
Annen flatfisk    2399.0                  4
Annen flyndre     2329.0                416
Annen laksefisk   799.0                   1
                                       ...
Vassild           742.0                 280
Villsvinfisk      1421.0                  7
Vågehval          2729.0                296
Ål                811.0                   2
Øyepål            1036.0               2210
Length: 122, dtype: int64

In [237]:
average_weight_per_fish_type = df.groupby(['Art - FDIR', 'Art - FDIR (kode)'])['Rundvekt'].mean().reset_index(name='Average Weight')
average_weight_per_fish_type.sort_values

<bound method DataFrame.sort_values of            Art - FDIR  Art - FDIR (kode)  Average Weight
0               Akkar             2634.0       68.892857
1    Annen blekksprut             2639.0       18.750000
2      Annen flatfisk             2399.0      710.000000
3       Annen flyndre             2329.0      112.548077
4     Annen laksefisk              799.0        8.000000
..                ...                ...             ...
117           Vassild              742.0    52269.567857
118      Villsvinfisk             1421.0       32.285714
119          Vågehval             2729.0     1428.445946
120                Ål              811.0        1.000000
121            Øyepål             1036.0    11312.888235

[122 rows x 3 columns]>

In [238]:
# Slå sammen Bruttotonnasjekolonnene - Tar utgangspunkt i at det ikke er særlig stor forskjell på Bruttotonnasje 1969 og 
# Bruttotonnasje annen, da dette bare er forskjellige klassifiseringsmetoder for lastekapasitet(Hulrom i skipet).

df['Bruttotonnasje Kombinert'] = df['Bruttotonnasje 1969'].fillna(df['Bruttotonnasje annen'])

# Dropper unødvendig informasjon. Tabellen inneholder masse duplikater. som egen kolonne for navn og for kode
# Forskjellige klassifiseringsmåter. Holder på FDIR sine.

df.drop(columns = ['Meldingsdato', 
                   'Meldingsklokkeslett', 
                   'Startdato', 
                   'Startklokkeslett', 
                   'Hovedområde start', 
                   'Lokasjon start (kode)', 
                   'Stoppdato', 
                   'Stoppklokkeslett', 
                   'Fangstår', 
                   'Hovedområde stopp (kode)', 
                   'Hovedområde stopp', 
                   'Lokasjon stopp (kode)', 
                   'Redskap FAO (kode)', 
                   'Redskap FAO', 
                   'Redskap FDIR', 
                   'Hovedart FAO (kode)', 
                   'Hovedart FAO', 
                   'Art FAO (kode)',
                   'Art FAO',
                   'Art - FDIR',
                   'Art - gruppe', 
                   'Lengdegruppe', 
                   'Bredde', 
                   'Fartøylengde',
                   'Bruttotonnasje 1969',
                   'Bruttotonnasje annen'
    ], inplace=True)

In [239]:
df.head()

,Melding ID,Meldingstidspunkt,Starttidspunkt,Startposisjon bredde,Startposisjon lengde,Hovedområde start (kode),Havdybde start,Stopptidspunkt,Varighet,Stopposisjon bredde,Stopposisjon lengde,Havdybde stopp,Trekkavstand,Redskap FDIR (kode),Hovedart - FDIR (kode),Art - FDIR (kode),Art - gruppe (kode),Rundvekt,Lengdegruppe (kode),Bruttotonnasje Kombinert
0,1497177,01.01.2018,31.12.2017,-60.350,-46.133,NaN,-2740,01.01.2018,1440,-60.400,-46.150,-805,5649.0,53.0,2513.0,2513.0,506.0,706714.0,5.0,9432.0
1,1497178,01.01.2018,30.12.2017 23:21,74.885,16.048,20.0,-335,31.12.2017 04:16,295,74.914,15.969,-334,3970.0,51.0,1027.0,1027.0,202.0,9594.0,5.0,1476.0
2,1497178,01.01.2018,30.12.2017 23:21,74.885,16.048,20.0,-335,31.12.2017 04:16,295,74.914,15.969,-334,3970.0,51.0,1027.0,1022.0,201.0,8510.0,5.0,1476.0
3,1497178,01.01.2018,30.12.2017 23:21,74.885,16.048,20.0,-335,31.12.2017 04:16,295,74.914,15.969,-334,3970.0,51.0,1027.0,2313.0,301.0,196.0,5.0,1476.0
4,1497178,01.01.2018,30.12.2017 23:21,74.885,16.048,20.0,-335,31.12.2017 04:16,295,74.914,15.969,-334,3970.0,51.0,1027.0,1032.0,203.0,134.0,5.0,1476.0

In [240]:
# Ser her at nokre meldinger har opptil 54 forskjellige rapporteringer. Rekner med det handler om bifangst.
df['Melding ID'].value_counts()

Melding ID
1657367    54
1646724    50
1654624    46
1601430    44
1695415    44
           ..
1669448     1
1669459     1
1669509     1
1669524     1
1497177     1
Name: count, Length: 49437, dtype: int64

In [241]:
filtered_df = df[df['Melding ID'] == 1657367]
filtered_df

,Melding ID,Meldingstidspunkt,Starttidspunkt,Startposisjon bredde,Startposisjon lengde,Hovedområde start (kode),Havdybde start,Stopptidspunkt,Varighet,Stopposisjon bredde,Stopposisjon lengde,Havdybde stopp,Trekkavstand,Redskap FDIR (kode),Hovedart - FDIR (kode),Art - FDIR (kode),Art - gruppe (kode),Rundvekt,Lengdegruppe (kode),Bruttotonnasje Kombinert
131369,1657367,24.05.2018 23:35,24.05.2018 03:01,60.489,2.922,28.0,-105,24.05.2018 05:00,119,60.493,2.884,-103,2136.0,61.0,1032.0,1032.0,203.0,624.0,4.0,321.0
131370,1657367,24.05.2018 23:35,24.05.2018 03:01,60.489,2.922,28.0,-105,24.05.2018 05:00,119,60.493,2.884,-103,2136.0,61.0,1032.0,1051.0,220.0,378.0,4.0,321.0
131371,1657367,24.05.2018 23:35,24.05.2018 03:01,60.489,2.922,28.0,-105,24.05.2018 05:00,119,60.493,2.884,-103,2136.0,61.0,1032.0,1022.0,201.0,224.0,4.0,321.0
131372,1657367,24.05.2018 23:35,24.05.2018 03:01,60.489,2.922,28.0,-105,24.05.2018 05:00,119,60.493,2.884,-103,2136.0,61.0,1032.0,1027.0,202.0,137.0,4.0,321.0
131373,1657367,24.05.2018 23:35,24.05.2018 03:01,60.489,2.922,28.0,-105,24.05.2018 05:00,119,60.493,2.884,-103,2136.0,61.0,1032.0,1023.0,220.0,96.0,4.0,321.0
131374,1657367,24.05.2018 23:35,24.05.2018 05:00,60.493,2.884,28.0,-103,24.05.2018 07:07,127,60.511,2.955,-108,4387.0,61.0,1051.0,1051.0,220.0,378.0,4.0,321.0
131375,1657367,24.05.2018 23:35,24.05.2018 05:00,60.493,2.884,28.0,-103,24.05.2018 07:07,127,60.511,2.955,-108,4387.0,61.0,1051.0,1022.0,201.0,201.0,4.0,321.0
131376,1657367,24.05.2018 23:35,24.05.2018 05:00,60.493,2.884,28.0,-103,24.05.2018 07:07,127,60.511,2.955,-108,4387.0,61.0,1051.0,1032.0,203.0,96.0,4.0,321.0
131377,1657367,24.05.2018 23:35,24.05.2018 05:00,60.493,2.884,28.0,-103,24.05.2018 07:07,127,60.511,2.955,-108,4387.0,61.0,1051.0,1023.0,220.0,48.0,4.0,321.0
131378,1657367,24.05.2018 23:35,24.05.2018 05:00,60.493,2.884,28.0,-103,24.05.2018 07:07,127,60.511,2.955,-108,4387.0,61.0,1051.0,2411.0,320.0,48.0,4.0,321.0
131379,1657367,24.05.2018 23:35,24.05.2018 05:00,60.493,2.884,28.0,-103,24.05.2018 07:07,127,60.511,2.955,-108,4387.0,61.0,1051.0,1034.0,220.0,46.0,4.0,321.0
131380,1657367,24.05.2018 23:35,24.05.2018 05:00,60.493,2.884,28.0,-103,24.05.2018 07:07,127,60.511,2.955,-108,4387.0,61.0,1051.0,1027.0,202.0,45.0,4.0,321.0
131381,1657367,24.05.2018 23:35,24.05.2018 05:00,60.493,2.884,28.0,-103,24.05.2018 07:07,127,60.511,2.955,-108,4387.0,61.0,1051.0,2312.0,320.0,38.0,4.0,321.0
131382,1657367,24.05.2018 23:35,24.05.2018 07:07,60.511,2.956,28.0,-108,24.05.2018 08:53,106,60.519,2.962,-112,950.0,61.0,1032.0,1032.0,203.0,144.0,4.0,321.0
131383,1657367,24.05.2018 23:35,24.05.2018 07:07,60.511,2.956,28.0,-108,24.05.2018 08:53,106,60.519,2.962,-112,950.0,61.0,1032.0,1051.0,220.0,126.0,4.0,321.0
131384,1657367,24.05.2018 23:35,24.05.2018 07:07,60.511,2.956,28.0,-108,24.05.2018 08:53,106,60.519,2.962,-112,950.0,61.0,1032.0,1022.0,201.0,118.0,4.0,321.0
131385,1657367,24.05.2018 23:35,24.05.2018 07:07,60.511,2.956,28.0,-108,24.05.2018 08:53,106,60.519,2.962,-112,950.0,61.0,1032.0,2411.0,320.0,96.0,4.0,321.0
131386,1657367,24.05.2018 23:35,24.05.2018 07:07,60.511,2.956,28.0,-108,24.05.2018 08:53,106,60.519,2.962,-112,950.0,61.0,1032.0,1027.0,202.0,91.0,4.0,321.0
131387,1657367,24.05.2018 23:35,24.05.2018 07:07,60.511,2.956,28.0,-108,24.05.2018 08:53,106,60.519,2.962,-112,950.0,61.0,1032.0,2311.0,320.0,88.0,4.0,321.0
131388,1657367,24.05.2018 23:35,24.05.2018 07:07,60.511,2.956,28.0,-108,24.05.2018 08:53,106,60.519,2.962,-112,950.0,61.0,1032.0,1023.0,220.0,48.0,4.0,321.0
131389,1657367,24.05.2018 23:35,24.05.2018 09:02,60.527,2.970,28.0,-116,24.05.2018 10:38,96,60.541,2.974,-118,1575.0,61.0,1032.0,1032.0,203.0,288.0,4.0,321.0
131390,1657367,24.05.2018 23:35,24.05.2018 09:02,60.527,2.970,28.0,-116,24.05.2018 10:38,96,60.541,2.974,-118,1575.0,61.0,1032.0,1027.0,202.0,91.0,4.0,321.0
131391,1657367,24.05.2018 23:35,24.05.2018 09:02,60.527,2.970,28.0,-116,24.05.2018 10:38,96,60.541,2.974,-118,1575.0,61.0,1032.0,1051.0,220.0,84.0,4.0,321.0
131392,1657367,24.05.2018 23:35,24.05.2018 09:02,60.527,2.970,28.0,-116,24.05.2018 10:38,96,60.541,2.974,-118,1575.0,61.0,1032.0,1022.0,201.0,71.0,4.0,321.0
131393,1657367,24.05.2018 23:35,24.05.2018 09:02,60.527,2.970,28.0,-116,24.05.2018 10:38,96,60.541,2.974,-118,1575.0,61.0,1032.0,1719.0,304.0,44.0,4.0,321.0
131394,1657367,24.05.2018 23:35,24.05.2018 11:13,60.540,2.934,28.0,-115,24.05.2018 13:15,122,60.490,2.860,-105,6896.0,61.0,1032.0,1032.0,203.0,384.0,4.0,321.0
131395,1657367,24.05.2018 23:35,24.05.2018 11:13,60.540,2.934,28.0,-115,24.05.2018 13:15,122,60.490,2.860,-105,6896.0,61.0,1032.0,1022.0,201.0,248.0,4.0,321.0
131396,1657367,24.05.2018 23:35,24.05.2018 11:13,60.540,2.934,28.0,-115,24.05.2018 13:15,122,60.490,2.860,-105,6896.0,61.0,1032.0,1051.0,220.0,210.0,4.0,321.0
131397,1657367,24.05.2018 23:35,24.05.2018 11:13,60.540,2.934,28.0,-115,24.05.2018 13:15,122,60.490,2.860,-105,6896.0,61.0,1032.0,1027.0,202.0,182.0,4.0,321.0
131398,1657367,24.05.2018 23:35,24.05.2018 11:13,60.540,2.934,28.0,-115,24.05.2018 13:15,122,60.490,2.860,-105,6896.0,61.0,1032.0,1023.0,220.0,144.0,4.0,321.0
131399,1657367,24.05.2018 23:35,24.05.2018 11:13,60.540,2.934,28.0,-115,24.05.2018 13:15,122,60.490,2.860,-105,6896.0,61.0,1032.0,2411.0,320.0,48.0,4.0,321.0
131400,1657367,24.05.2018 23:35,24.05.2018 11:13,60.540,2.934,28.0,-115,24.05.2018 13:15,122,60.490,2.860,-105,6896.0,61.0,1032.0,2318.0,320.0,38.0,4.0,321.0
131401,1657367,24.05.2018 23:35,24.05.2018 13:15,60.490,2.860,28.0,-105,24.05.2018 15:15,120,60.460,2.862,-106,3344.0,61.0,1027.0,1027.0,202.0,228.0,4.0,321.0
131402,1657367,24.05.2018 23:35,24.05.2018 13:15,60.490,2.860,28.0,-105,24.05.2018 15:15,120,60.460,2.862,-106,3344.0,61.0,1027.0,1022.0,201.0,165.0,4.0,321.0
131403,1657367,24.05.2018 23:35,24.05.2018 13:15,60.490,2.860,28.0,-105,24.05.2018 15:15,120,60.460,2.862,-106,3344.0,61.0,1027.0,1051.0,220.0,126.0,4.0,321.0
131404,1657367,24.05.2018 23:35,24.05.2018 13:15,60.490,2.860,28.0,-105,24.05.2018 15:15,120,60.460,2.862,-106,3344.0,61.0,1027.0,1032.0,203.0,96.0,4.0,321.0
131405,1657367,24.05.2018 23:35,24.05.2018 13:15,60.490,2.860,28.0,-105,24.05.2018 15:15,120,60.460,2.862,-106,3344.0,61.0,1027.0,1023.0,220.0,48.0,4.0,321.0
131406,1657367,24.05.2018 23:35,24.05.2018 13:15,60.490,2.860,28.0,-105,24.05.2018 15:15,120,60.460,2.862,-106,3344.0,61.0,1027.0,2411.0,320.0,48.0,4.0,321.0
131407,1657367,24.05.2018 23:35,24.05.2018 13:15,60.490,2.860,28.0,-105,24.05.2018 15:15,120,60.460,2.862,-106,3344.0,61.0,1027.0,2311.0,320.0,44.0,4.0,321.0
131408,1657367,24.05.2018 23:35,24.05.2018 15:21,60.460,2.838,28.0,-107,24.05.2018 17:20,119,60.449,2.905,-103,3886.0,61.0,1022.0,1022.0,201.0,224.0,4.0,321.0
131409,1657367,24.05.2018 23:35,24.05.2018 15:21,60.460,2.838,28.0,-107,24.05.2018 17:20,119,60.449,2.905,-103,3886.0,61.0,1022.0,1023.0,220.0,48.0,4.0,321.0
131410,1657367,24.05.2018 23:35,24.05.2018 15:21,60.460,2.838,28.0,-107,24.05.2018 17:20,119,60.449,2.905,-103,3886.0,61.0,1022.0,2411.0,320.0,48.0,4.0,321.0
131411,1657367,24.05.2018 23:35,24.05.2018 15:21,60.460,2.838,28.0,-107,24.05.2018 17:20,119,60.449,2.905,-103,3886.0,61.0,1022.0,1027.0,202.0,45.0,4.0,321.0
131412,1657367,24.05.2018 23:35,24.05.2018 15:21,60.460,2.838,28.0,-107,24.05.2018 17:20,119,60.449,2.905,-103,3886.0,61.0,1022.0,1051.0,220.0,42.0,4.0,321.0
131413,1657367,24.05.2018 23:35,24.05.2018 15:21,60.460,2.838,28.0,-107,24.05.2018 17:20,119,60.449,2.905,-103,3886.0,61.0,1022.0,2312.0,320.0,38.0,4.0,321.0
131414,1657367,24.05.2018 23:35,24.05.2018 17:20,60.449,2.905,28.0,-103,24.05.2018 18:59,99,60.441,2.935,-102,1877.0,61.0,1027.0,1027.0,202.0,456.0,4.0,321.0
131415,1657367,24.05.2018 23:35,24.05.2018 17:20,60.449,2.905,28.0,-103,24.05.2018 18:59,99,60.441,2.935,-102,1877.0,61.0,1027.0,1022.0,201.0,401.0,4.0,321.0
131416,1657367,24.05.2018 23:35,24.05.2018 17:20,60.449,2.905,28.0,-103,24.05.2018 18:59,99,60.441,2.935,-102,1877.0,61.0,1027.0,1051.0,220.0,330.0,4.0,321.0
131417,1657367,24.05.2018 23:35,24.05.2018 17:20,60.449,2.905,28.0,-103,24.05.2018 18:59,99,60.441,2.935,-102,1877.0,61.0,1027.0,1032.0,203.0,288.0,4.0,321.0
131418,1657367,24.05.2018 23:35,24.05.2018 17:20,60.449,2.905,28.0,-103,24.05.2018 18:59,99,60.441,2.935,-102,1877.0,61.0,1027.0,1023.0,220.0,96.0,4.0,321.0
131419,1657367,24.05.2018 23:35,24.05.2018 17:20,60.449,2.905,28.0,-103,24.05.2018 18:59,99,60.441,2.935,-102,1877.0,61.0,1027.0,2411.0,320.0,48.0,4.0,321.0
131420,1657367,24.05.2018 23:35,24.05.2018 17:20,60.449,2.905,28.0,-103,24.05.2018 18:59,99,60.441,2.935,-102,1877.0,61.0,1027.0,1719.0,304.0,44.0,4.0,321.0
131421,1657367,24.05.2018 23:35,24.05.2018 17:20,60.449,2.905,28.0,-103,24.05.2018 18:59,99,60.441,2.935,-102,1877.0,61.0,1027.0,1039.0,220.0,40.0,4.0,321.0
131422,1657367,24.05.2018 23:35,24.05.2018 17:20,60.449,2.905,28.0,-103,24.05.2018 18:59,99,60.441,2.935,-102,1877.0,61.0,1027.0,2312.0,320.0,38.0,4.0,321.0

In [242]:
df['Havdybde stopp'].value_counts()

Havdybde stopp
-108     1413
-145     1392
-149     1369
-128     1347
-119     1324
         ...
-3408       1
-3225       1
-811        1
-1379       1
-1244       1
Name: count, Length: 2378, dtype: int64

In [243]:
depth_analysis = df.groupby('Havdybde start')['Rundvekt'].sum().reset_index()

# Sort the results for better visualization
depth_analysis_sorted = depth_analysis.sort_values(by='Rundvekt', ascending=False)

# Display the result
print(depth_analysis_sorted)

      Havdybde start    Rundvekt
2142            -126  13627074.0
2144            -124  12839331.0
2151            -117  12313017.0
2140            -128  12167537.0
2145            -123  11920745.0
...              ...         ...
695            -1958         0.0
691            -1963         0.0
666            -2005         0.0
658            -2020         0.0
2374            1220         0.0

[2375 rows x 2 columns]

In [244]:
# Group by species and sum catch weight
species_weight = df.groupby('Art - FDIR')['Rundvekt'].sum().reset_index()

# Optionally, sort the results by weight for better visualization
species_weight_sorted = species_weight.sort_values(by='Rundvekt', ascending=False)

# Display the result
print(species_weight_sorted)

KeyError: 'Art - FDIR'